# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application In Windows

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest] #, macos-latest, 'ubuntu-latest']
        
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        
    - name: Install uv
      uses: astral-sh/setup-uv@v6.4.3
      with:
        version: "latest"
        enable-cache: true
        
    - run: uv sync
      working-directory: numerology_cli
      
    - run: uv run powershell scripts/windows/numerology-cli-setup.bat
      if: matrix.os == 'windows-latest'
      env:
        VIRTUAL_ENV: numerology_cli/.venv
    
    - name: upload artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: numerology-cli_win_snapshot
        path: dist/numerology-cli
